### ISSUE TITLE
Error/Cant Open Main.Py

### ISSUE THREAD

**Issue by XVR1212** [will7200/Yugioh-bot#11]
I keep getting this error when I try to open "Main.Py"

2017-12-13 16:59:35,711 - bot.debug_helpers - DEBUG - Setup Complete
2017-12-13 16:59:35,714 - bot - DEBUG - Setup Complete
Traceback (most recent call last):
  File "C:\Users\User\Desktop\sdawf\Yugioh-bot\main.py", line 14, in <module>
    from bot.providers import get_provider
  File "C:\Users\User\Desktop\sdawf\Yugioh-bot\bot\providers\__init__.py", line 1, in <module>
    from .provider import Provider
  File "C:\Users\User\Desktop\sdawf\Yugioh-bot\bot\providers\provider.py", line 11, in <module>
    from bot.duel_links_runtime import DuelLinkRunTime
  File "C:\Users\User\Desktop\sdawf\Yugioh-bot\bot\duel_links_runtime.py", line 25, in <module>
    class DuelLinkRunTimeOptions(object):
  File "C:\Users\User\Desktop\sdawf\Yugioh-bot\bot\duel_links_runtime.py", line 27, in DuelLinkRunTimeOptions
    _last_run_at = datetime.datetime.fromtimestamp(0)
OSError: [Errno 22] Invalid argument

**Comment by will7200** [comment]
That's weird, that is indicating that the function failed. Can you give me your python version and operating system version(i.e. windows 10, windows 7, etc.).

**Comment by XVR1212** [comment]
Currently my Python version is 3.6

But I ran it with version 3.5.3 and I get the same error

I have Windows 10 Pro

(if you want I can download version 3.5.3 again)

**Comment by will7200** [comment]
Ok I tested this against a python 3.6.3 env and the fromtimestamp call with less than 86400 as the first argument fails. In python 3.5.3 it doesn't fail. I will hopefully get a pic out today.

**Comment by will7200** [comment]
Ok I changed the default timestamp to after 1970. I tested against 3.6.3.
392954d1fa80f3c5830df3af43f302c15d16acc2
