### ISSUE TITLE
Error when the app is launch(python main.py bot -s)

### ISSUE THREAD

**Issue by 08A** [will7200/Yugioh-bot#20]
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    cli()
  File "C:\python\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 90, in bot
    dlRuntime = setup_runtime(uconfig)
  File "main.py", line 38, in setup_runtime
    from bot.providers import get_provider
  File "C:\Users\root\Downloads\Yugioh-bot-master\bot\providers\__init__.py", line 2, in <module>
    from bot.providers.nox import Nox
  File "C:\Users\root\Downloads\Yugioh-bot-master\bot\providers\nox\__init__.py", line 1, in <module>
    from .nox import Nox
  File "C:\Users\root\Downloads\Yugioh-bot-master\bot\providers\nox\nox.py", line 16, in <module>
    from bot.providers.nox.predefined import NoxPredefined, duel_variant_v
  File "C:\Users\root\Downloads\Yugioh-bot-master\bot\providers\nox\predefined.py", line 24, in <module>
    class NoxPredefined(Predefined):
  File "C:\Users\root\Downloads\Yugioh-bot-master\bot\providers\nox\predefined.py", line 50, in NoxPredefined
    details="App is not opened through ADB Call instead of ui touch event")
  File "C:\python\lib\site-packages\deprecation.py", line 131, in deprecated
    current_version = version.StrictVersion(current_version)
  File "C:\python\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\python\lib\distutils\version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0'

**Comment by will7200** [comment]
It seems that you are using an old version, try this command
```bash
git reset --hard origin/master
```
I also renamed the clean_version type in 82b44cdca358ba11ac42b7b93d8fb8dce7938c4a

**Comment by 08A** [comment]
ok ty
