### ISSUE TITLE
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in cv::imdecode_

### ISSUE THREAD

**Issue by apert4160** [will7200/Yugioh-bot#22]
[full-log.txt](https://github.com/will7200/Yugioh-bot/files/1613639/log.txt)

Hi, i got some trouble when i was running the bot, could you provide any help?

A part of error log: 
```
2018-01-09 09:59 - DEBUG - bot - Timeout dump Scheduled
2018-01-09 09:59 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.main.<locals>.in_main" to job store "default"
2018-01-09 09:59 - INFO - bot - Tracking F:\WorkSpaces\Python\Yugioh-bot\runTimeOptions.json
2018-01-09 09:59 - INFO - bot - Next run at 2018-01-09T09:59:24.965090
2018-01-09 09:59 - INFO - apscheduler.executors.default - Running job "DuelLinkRunTime.main.<locals>.in_main (trigger: date[2018-01-09 09:59:24 CST], next run at: 2018-01-09 09:59:24 CST)" (scheduled at 2018-01-09 09:59:24.965090
+08:00)
2018-01-09 09:59 - INFO - apscheduler.scheduler - Removed job cron_main_at_2018-01-09T09:59:24.965090
2018-01-09 09:59 - INFO - bot - Value last_run_at modified to 2018-01-09 09:59:24.970718
2018-01-09 09:59 - DEBUG - bot - Timeout dump Scheduled
2018-01-09 09:59 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
error: closed
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in cv::imdecode_, file C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp, line 637
2018-01-09 09:59 - DEBUG - bot - <class 'cv2.error'> duel_links_runtime.py 327
2018-01-09 09:59 - DEBUG - bot - Traceback (most recent call last):
  File "F:\WorkSpaces\Python\Yugioh-bot\bot\duel_links_runtime.py", line 327, in in_main
    provider.compare_with_back_button()
  File "F:\WorkSpaces\Python\Yugioh-bot\bot\providers\nox\nox.py", line 251, in compare_with_back_button
    img = self.get_img_from_screen_shot()
  File "F:\WorkSpaces\Python\Yugioh-bot\bot\providers\actions.py", line 38, in get_img_from_screen_shot
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
cv2.error: C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:637: error: (-215) !buf.empty() && buf.isContinuous() in function cv::imdecode_

```

Some environment info:
```
Nox version: 6.0.1.1
System version: Windows7
System type: 64
CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
CPU core count: 4
Total memory: 8096MB
Available memory: 2471MB
CPU VT: Enabled
Rendering mode: OpenGL
OpenGL rendering: Intel(R) HD Graphics 5500
Discrete graphics: Enabled
Graphics card1: Intel(R) HD Graphics 5500
Firewall: Enabled(Recommend to disable)
```
Using python 3.5.4

Is this may cause by i'm using a Chinese system language? I've already change the Nox language and the  game language to English, still could run it successful.

Appreciate it.

**Comment by will7200** [comment]
Something is going on with the image retrieval from Nox command.
Try this command in the root directory:
```bash
bin\\adb.exe shell "screencap -p | busybox base64"
```
Its gonna be long

**Comment by apert4160** [comment]
From your solution, I consider it may cause by the Android official tools, i've installed the official Android tools before and config the path in the `System Environment Variables`. 
I will try to edit the Environment Variables make it point to `adb.exe` which one i copy from Nox(`nox_adb.exe`) and rename it. (just like the docs said?)
Seems like the Game Server just running on upgrade progression, i will try it later and send some feedback.
Thank you for your reply.

**Comment by apert4160** [comment]
The issue still exist.

As i run `bin\\adb.exe shell "screencap -p | busybox base64"`, got this msg return
```
error: no devices/emulators found
```

What should i support to do now?

**Comment by apert4160** [comment]
I think i just figure out what's happening on my issue.


Due to the fact that [GFW](https://en.wikipedia.org/wiki/Great_Firewall) has block the Game Server, so i have to activity [this app](https://github.com/shadowsocksr-backup/shadowsocksr-android/releases) on the Nox Android to create a VPN connection, in order to break the wall.


According to this [Nox offical Tutorial](https://www.bignox.com/blog/how-to-connect-android-studio-with-nox-app-player-for-android-development-and-debug/), i turn on the `root mode` on Nox Setting and activity the `Developer mode` on the Android, restart the Android and finally i can using an adb command `adb.exe connect [ANDROID IP]:[PROT]` to connect my Android, and it seems works fine.
```
F:\WorkSpaces\Python\Yugioh-bot\bin>adb.exe connect 127.0.0.1:52001
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 127.0.0.1:52001

F:\WorkSpaces\Python\Yugioh-bot\bin>adb.exe devices
List of devices attached
127.0.0.1:52001 device
```

I try this command you give me and it finally work: 
```
F:\WorkSpaces\Python\Yugioh-bot\bin>adb.exe shell "screencap -p | busybox base64"

6WqH23/b4zv0WL/dZ0797Huct3YYQ1XVXH3fU/zub36Zxfy4U05/4af/A37rt7+hpzlzgmpzc8yK
xY/kDGpj6YBgcVpyg5bOxGIRGksCbK6pHc4NxmBoqCrH
...(too much output)
```


**BUT**, once i activity the app i said before, created a VPN connection, than i try this command again, it show out like this:
```
F:\WorkSpaces\Python\Yugioh-bot\bin>adb.exe shell "screencap -p | busybox base64"
error: closed

F:\WorkSpaces\Python\Yugioh-bot\bin>adb.exe shell "screencap -p | busybox base64"
error: no devices/emulators found
```

So i have to restart the Android that i can use `adb` to connect my Android again.


I guess the `adb shell "screencap -p | busybox base64"` command just using the some port with the VPN connection? Or something else conflicts between them?


I have to try to build a network bridge between my computer and the Android, so i can connect to the Game Server without running a VPN app. 


Such upset, but thank you anywhere.

**Comment by will7200** [comment]
If you have the steam version maybe you can bypass the issue?
