### ISSUE TITLE
[Installation] Win32gui does not import correctly

### ISSUE THREAD

**Issue by phongs** [will7200/Yugioh-bot#26]
When I run 'python main.py bot -s' I get the following error:

`Z:\python35>python main.py bot -s
2018-01-14 16:09:30,376 - bot - CRITICAL - Clean version is wrong (0) cannot be zero something happened
2018-01-14 16:09:30,376 - bot - CRITICAL - Try running git reset --hard origin/master
Z:\python35\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    cli()
  File "Z:\python35\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "Z:\python35\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "Z:\python35\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "Z:\python35\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "Z:\python35\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 94, in bot
    dlRuntime = setup_runtime(uconfig)
  File "main.py", line 41, in setup_runtime
    from bot.providers import get_provider
  File "Z:\python35\bot\providers\__init__.py", line 2, in <module>
    from bot.providers.nox import Nox
  File "Z:\python35\bot\providers\nox\__init__.py", line 1, in <module>
    from .nox import Nox
  File "Z:\python35\bot\providers\nox\nox.py", line 6, in <module>
    import win32gui
ImportError: No module named 'win32gui'`

No module named win32gui, yet if I run 'python -m pip install win32gui' it says requirements are already satisfied. I'm running Windows 10, with Python 3.5.

Also if I try running 'pythonw main.py gui -s' a window appears and disappears quickly and that's it.

Hopefully you can help. Thanks!

**Comment by curtiola** [comment]
You need to install pywin32
https://sourceforge.net/projects/pywin32/files/pywin32/

**Comment by phongs** [comment]
I downloaded pywin32-221.win-amd64-py3.5.exe, and was able to get past the win32gui problem. But now I'm receiving this error:
`  File "Z:\python35\bot\providers\nox\predefined.py", line 50, in NoxPredefined
    details="App is not opened through ADB Call instead of ui touch event")
  File "Z:\python35\lib\site-packages\deprecation.py", line 131, in deprecated
    current_version = version.StrictVersion(current_version)
  File "Z:\python35\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "Z:\python35\lib\distutils\version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0'`

Any ideas?

**Comment by phongs** [comment]
I have definitely installed everything with no errors. I've ran pip install depracation and it said requirement satisfied. Looking at your picture I noticed I was missing adb and adbwinapi.dll, so I copied it over and renamed from my Nox folder. But it looks like I'm still receiving the same error when I try to run the bot, and when I try to run gui it just opens/closes right away. 

I'm getting closer! haha.. Does the bot open Nox/Steam up itself? Or should you have the game open already?

**Comment by curtiola** [comment]
I have the game open in Nox already when I run the bot, I haven't used it with steam yet.
Oh, also, `python main.py gui -s` works for me, not sure if that "w" is a typo or not.. lol

**Comment by koreplay** [comment]
When you installed tessarect did you install it to the right path?

**Comment by curtiola** [comment]
I assume he did since he didn't mention the tess folder being missing when comparing our ...\bin folders
& the error doesn't say anything about tess or ocr.png

**Comment by koreplay** [comment]
My folder looks different than both of yours and my bot semi works just that it clicks random spots at times 
![comapre](https://user-images.githubusercontent.com/8702345/34921915-4a5aa54a-f93d-11e7-874e-2a4d8e251a01.png)

**Comment by curtiola** [comment]
We were comparing our "...\Yugioh-bot\bin" folder, not the root directory.
& the random clicking is normal since it looks for circles, 
sometimes there are circles in the pixels you can't see.

**Comment by phongs** [comment]
I installed Tess directly to the tess folder in the bot. I was only missing the adb file and dll.

**Comment by curtiola** [comment]
ruuning `python install.py` should have copied those files from the Nox bin for you, so if those were missing, perhaps it didn't run properly?

**Comment by phongs** [comment]
Here's what it looks like when I run install.py.

`Make sure you run this from the root directory of Yugioh-Bot
Installing Required components to get this bot up and running
Component 0: Creating Temp Folder
Running `mkdir tmp`
A subdirectory or file tmp already exists.
Component 1: Installing Tesseract
Running `bin\tess\tesseract.exe -v`
Looks like tesseract is installed already
Component 2: Copying nox files required
Running `cp "C:\Program Files (x86)\Nox\bin\nox_adb.exe" bin/adb.exe`
'cp' is not recognized as an internal or external command,
operable program or batch file.
Running `cp "C:\Program Files (x86)\Nox\bin\AdbWinApi.dll" bin/`
'cp' is not recognized as an internal or external command,
operable program or batch file.
Copied [nox_adb.exe, AdbWinApi.dll] into bin folder
Component 3: Checking required packages
All required packages found`

As you can see it looks like 'cp' is not recognized as an internal or external command is the reason the files weren't copied over.

**Comment by will7200** [comment]
Cp command is a defacto present in Windows and Linux that allows copying files seems weird that it failed.

**Comment by will7200** [comment]
If you are still having the version error try this:
https://github.com/will7200/Yugioh-bot/issues/29#issuecomment-357773668

**Comment by phongs** [comment]
I tried the git pull, git reset --hard origin/master. Now I'm getting a different error. Progress! Here's what it's displaying:

`Z:\python35\Yugioh-bot>python main.py gui -s
Z:\python35\Yugioh-bot\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-01-15 14:06 - DEBUG - bot - Watching Z:\python35\Yugioh-bot\runTimeOptions.json for runTime Options
2018-01-15 14:06 - INFO - apscheduler.scheduler - Scheduler started
2018-01-15 14:06 - DEBUG - bot - Value next_run_at modified to 2018-01-15 14:06:23.269216
2018-01-15 14:06 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dump" to job store "default"
2018-01-15 14:06 - DEBUG - bot - Timeout dump Scheduled
2018-01-15 14:06 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.main.<locals>.in_main" to job store "default"
2018-01-15 14:06 - INFO - bot - Tracking Z:\python35\Yugioh-bot\runTimeOptions.json
2018-01-15 14:06 - INFO - bot - Next run at 2018-01-15T14:06:23.269216
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    cli()
  File "Z:\python35\Yugioh-bot\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "Z:\python35\Yugioh-bot\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "Z:\python35\Yugioh-bot\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "Z:\python35\Yugioh-bot\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "Z:\python35\Yugioh-bot\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 132, in gui
    window = DuelLinksGui(dlRuntime, uconfig.get('locations','assets'))
  File "Z:\python35\Yugioh-bot\bot\dl_gui.py", line 123, in __init__
    self.location_on_the_screen()
  File "Z:\python35\Yugioh-bot\bot\dl_gui.py", line 138, in location_on_the_screen
    self.move(x, y)
UnboundLocalError: local variable 'x' referenced before assignment`

**Comment by phongs** [comment]
That above error was when running main.py gui -s. I have now tried main.py bot -s, and it appears to be running. Although it doesn't seem to be running correctly... 

![Problems](https://i.imgur.com/qV5uWpc.png)

**Comment by phongs** [comment]
I've tried changing providers in the config to Steam and running the bot, still no luck. Here's what it looks like.
![error2](https://i.imgur.com/GxTBJdv.jpg)

**Comment by will7200** [comment]
Ok for the gui I fixed the issue you were having, you must have the taskbar in the top or right positions as I did not have code to account for that variation. Fixed in 27998841b18fab37adea42d4908b082e3c0decfc. Also for the steam provider It appears that the height and width differs that I have tested again. Can you provided me the details of your screen resolution for the steam app.

**Comment by phongs** [comment]
@will7200 I will update and try again. My screen resolution on this monitor is 1360x768 (kinda funky I know)..

**Comment by phongs** [comment]
@will7200 After updating I was able to run the gui and have it pop up, but the bot still doesn't seem to do anything but click around randomly. Is there a certain location my nox window needs to be, or is it reading directly from memory? Here's what the log is showing:
`Z:\python35\Yugioh-bot>python main.py gui -s
Z:\python35\Yugioh-bot\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-01-15 22:04 - DEBUG - bot - Value last_run_at modified to 2018-01-15 14:55:48.388847
2018-01-15 22:04 - INFO - apscheduler.scheduler - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2018-01-15 22:04 - DEBUG - bot - Timeout dump Scheduled
2018-01-15 22:04 - DEBUG - bot - Value next_run_at modified to 2018-01-15 18:56:19.864582
2018-01-15 22:04 - INFO - apscheduler.scheduler - Removed job b7763fd89dda48b9bd495933cfabe23b
2018-01-15 22:04 - INFO - apscheduler.scheduler - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2018-01-15 22:04 - DEBUG - bot - Timeout dump Scheduled
2018-01-15 22:04 - DEBUG - bot - Watching Z:\python35\Yugioh-bot\runTimeOptions.json for runTime Options
2018-01-15 22:04 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dump" to job store "default"
2018-01-15 22:04 - INFO - apscheduler.scheduler - Scheduler started
2018-01-15 22:04 - DEBUG - bot - Value next_run_at modified to 2018-01-15 22:04:02.954196
2018-01-15 22:04 - INFO - apscheduler.scheduler - Removed job 6da4d283115c4356880dec68dbbb98d0
2018-01-15 22:04 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dump" to job store "default"
2018-01-15 22:04 - DEBUG - bot - Timeout dump Scheduled
2018-01-15 22:04 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.main.<locals>.in_main" to job store "default"
2018-01-15 22:04 - INFO - bot - Tracking Z:\python35\Yugioh-bot\runTimeOptions.json
2018-01-15 22:04 - INFO - bot - Next run at 2018-01-15T22:04:02.954196
PyQt5.QtCore.QRect(0, 40, 1360, 728) PyQt5.QtCore.QRect(0, 0, 1360, 768)
2018-01-15 22:04 - INFO - apscheduler.executors.default - Running job "DuelLinkRunTime.main.<locals>.in_main (trigger: date[2018-01-15 22:04:02 CST], next run at: 2018-01-15 22:04:02 CST)" (scheduled at 2018-01-15 22:04:02.954196-06:00)
2018-01-15 22:04 - INFO - apscheduler.scheduler - Removed job cron_main_at_2018-01-15T22:04:02.954196
2018-01-15 22:04 - DEBUG - bot - Value last_run_at modified to 2018-01-15 22:04:02.954884
2018-01-15 22:04 - INFO - apscheduler.scheduler - Removed job 7aeb824b3e3d4c458809f9698db8a827
2018-01-15 22:04 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dump" to job store "default"
2018-01-15 22:04 - DEBUG - bot - Timeout dump Scheduled
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - INFO - bot - starting auto play through
2018-01-15 22:04 - INFO - bot.provider.Nox - starting auto run through
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Run through 1
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - INFO - apscheduler.executors.default - Running job "DuelLinkRunTime.dump (trigger: date[2018-01-15 22:04:07 CST], next run at: 2018-01-15 22:04:07 CST)" (scheduled at 2018-01-15 22:04:07.956388-06:00)
2018-01-15 22:04 - INFO - apscheduler.scheduler - Removed job a5ed93b4399940128344259e8edb078a
2018-01-15 22:04 - DEBUG - bot - Dump Getting Called {'last_run_at': datetime.datetime(2018, 1, 15, 22, 4, 2, 954884), 'playmode': 'autoplay', 'next_run_at': datetime.datetime(2018, 1, 15, 22, 4, 2, 954196), 'run_now': False, 'stop': False, 'battle_calls': {'beforeEnd': [], 'beforeStart': [], 'afterStart': [], 'afterEnd': []}}
2018-01-15 22:04 - INFO - apscheduler.executors.default - Job "DuelLinkRunTime.dump (trigger: date[2018-01-15 22:04:07 CST], next run at: 2018-01-15 22:04:07 CST)" executed successfully
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Tapping at location (348,640)
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - INFO - bot.provider.Nox - NPC Battle Mode,Points: (348,640) at location: (1), message: failure/Back-Button
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Tapping at location (28.846153846153847,767.5384615384615)
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR CLOSE BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOK FOR WORD 'OK', HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Tapping at location (170,582)
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR CLOSE BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOK FOR WORD 'OK', HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Tapping at location (330,338)
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - INFO - bot.provider.Nox - NPC Battle Mode,Points: (330,338) at location: (1), message: failure/Back-Button
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Tapping at location (30.666666666666668,768.3333333333334)
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR CLOSE BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOK FOR WORD 'OK', HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:04 - DEBUG - bot.provider.Nox - Tapping at location (66,604)
2018-01-15 22:05 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:05 - DEBUG - bot.provider.Nox - LOOKING FOR CLOSE BUTTON, HIGH CORRERLATION
2018-01-15 22:05 - DEBUG - bot.provider.Nox - LOOK FOR WORD 'OK', HIGH CORRERLATION
2018-01-15 22:05 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:05 - DEBUG - bot.provider.Nox - Tapping at location (264,588)
2018-01-15 22:05 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
2018-01-15 22:05 - DEBUG - bot.provider.Nox - LOOKING FOR BACK BUTTON, HIGH CORRERLATION
--- Logging error ---
Traceback (most recent call last):
  File "Z:\python35\Yugioh-bot\lib\logging\__init__.py", line 983, in emit
    stream.write(self.terminator)
OSError: raw write() returned invalid length 180 (should have been between 0 and 90)
Call stack:
  File "Z:\python35\Yugioh-bot\lib\threading.py", line 891, in _bootstrap
    self._bootstrap_inner()
  File "Z:\python35\Yugioh-bot\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "Z:\python35\Yugioh-bot\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "Z:\python35\Yugioh-bot\lib\concurrent\futures\thread.py", line 66, in _worker
    work_item.run()
  File "Z:\python35\Yugioh-bot\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "Z:\python35\Yugioh-bot\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "Z:\python35\Yugioh-bot\bot\duel_links_runtime.py", line 368, in in_main
    self.determine_playthrough(provider)
  File "Z:\python35\Yugioh-bot\bot\duel_links_runtime.py", line 327, in determine_playthrough
    provider.auto()
  File "Z:\python35\Yugioh-bot\bot\providers\provider.py", line 52, in auto
    self.scan()
  File "Z:\python35\Yugioh-bot\bot\providers\nox\nox.py", line 294, in scan
    loop_scan(self.compare_with_back_button, **{'info': dl_info})
  File "Z:\python35\Yugioh-bot\bot\providers\common.py", line 13, in loop_scan
    doit = fn(**kwargs)
  File "Z:\python35\Yugioh-bot\bot\providers\nox\nox.py", line 181, in compare_with_back_button
    self.root.debug("LOOKING FOR BACK BUTTON, {} CORRERLATION".format(corrword))
Message: 'LOOKING FOR BACK BUTTON, HIGH CORRERLATION'
Arguments: ()
2018-01-15 22:06 - DEBUG - bot.provider.Nox - LOOKING FOR CLOSE BUTTON, HIGH CORRERLATION
2018-01-15 22:06 - DEBUG - bot.provider.Nox - LOOK FOR WORD 'OK', HIGH CORRERLATION`

**Comment by will7200** [comment]
This is working correctly the algorithm to select opponents is not perfect and thus there will be false positives. As for your screen issue, I tested the steam against my and the resolution is maxed at 1600 something by 900 something and I can't shrink it so maybe I can do something of comparison so that image dimensions are no longer a problem.

**Comment by phongs** [comment]
It is working correctly! I just needed some patience. Thank you so much for all your help! What is your proper technique. Do you just leave it running in Autoplay mode all day or is there a trick I should know?

**Comment by will7200** [comment]
Basically I made this so it would auto duel the npcs while I went about my day. Help in events that require keys or dice.

**Comment by phongs** [comment]
Awesome. I started it this morning before work, I suppose if there's less
then 7 duelists when I get home I'll know it was working all day. Thanks
again!

**Comment by will7200** [comment]
Currently, It is set to run on startup and every 4 hours thereafter. I will eventually make a module that will allow the user to pick the schedule the bot runs at and maybe even monitor the current duelists avaiable.
