### ISSUE TITLE
ValueError: invalid version number '0'

### ISSUE THREAD

**Issue by alexandre0119** [will7200/Yugioh-bot#29]
Hi Dev,

Any idea why below issue happen? Just tried my first run, using Python3.6 and all requirements installed.

PS C:\Users\Alex\PycharmProjects\Yugioh-bot-master> python main.py gui -s
2018-01-14 15:13:30,478 - bot - CRITICAL - Clean version is wrong (0) cannot be zero something happened
2018-01-14 15:13:30,479 - bot - CRITICAL - Try running git reset --hard origin/master
C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    cli()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 130, in gui
    dlRuntime = setup_runtime(uconfig)
  File "main.py", line 41, in setup_runtime
    from bot.providers import get_provider
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot-master\bot\providers\__init__.py", line 2, in <module>
    from bot.providers.nox import Nox
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot-master\bot\providers\nox\__init__.py", line 1, in <module>
    from .nox import Nox
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot-master\bot\providers\nox\nox.py", line 15, in <module>
    from bot.providers.nox.predefined import NoxPredefined
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot-master\bot\providers\nox\predefined.py", line 24, in <module>
    class NoxPredefined(Predefined):
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot-master\bot\providers\nox\predefined.py", line 50, in NoxPredefined
    details="App is not opened through ADB Call instead of ui touch event")
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\deprecation.py", line 131, in deprecated
    current_version = version.StrictVersion(current_version)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36-32\lib\distutils\version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0'

Thanks,
Alex

**Comment by phongs** [comment]
Same error I'm getting with Python 3.5

**Comment by phongs** [comment]
Have you had any luck fixing this error? I've been trying since yesterday and I'm still getting the same ValueError: invalid version number '0' when I run the bot.

**Comment by will7200** [comment]
Give this a try
```
$ git reset --hard origin/master
```

**Comment by alexandre0119** [comment]
Issue got fixed with using Git to install, instead of manually downloading package. Close it for now.
