### ISSUE TITLE
[bug] encounter issue: [Errno 2] No such file or directory: 'tmp\\ocr.txt'

### ISSUE THREAD

**Issue by alexandre0119** [will7200/Yugioh-bot#32]
Hi Dev,

Encounter an issue when in auto battle screen, it is looking for tmp\ocr.txt but could not found. Pls help to take a look. thanks~
Settings:
- Win10
- Steam
- Python3.6
- Downloaded via Git

Logs:
-----------------------------------------------------------------------------------------------
2018-01-16 09:07 - DEBUG - bot.provider.Steam - Tapping at location (614,825)
2018-01-16 09:07 - INFO - bot.provider.Steam - Verifying battle
2018-01-16 09:07 - DEBUG - bot - <class 'FileNotFoundError'> duel_links_runtime.py 368
2018-01-16 09:07 - DEBUG - bot - Traceback (most recent call last):
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\duel_links_runtime.py", line 368, in in_main
    self.determine_playthrough(provider)
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\duel_links_runtime.py", line 327, in determine_playthrough
    provider.auto()
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\providers\provider.py", line 55, in auto
    raise e
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\providers\provider.py", line 52, in auto
    self.scan()
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\providers\steam\steam.py", line 212, in scan
    battle, version = self.verify_battle()
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\providers\provider.py", line 160, in verify_battle
    word = self.img_to_string(img, alpha_numeric).lower()
  File "C:\Users\Alex\PycharmProjects\Yugioh-bot\bot\providers\provider.py", line 221, in img_to_string
    with open("tmp\\ocr.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\ocr.txt'

2018-01-16 09:07 - DEBUG - bot - Value next_run_at modified to 2018-01-16 13:07:18.560115
2018-01-16 09:07 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dump" to job store "default"
2018-01-16 09:07 - DEBUG - bot - Timeout dump Scheduled
2018-01-16 09:07 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.main.<locals>.in_main" to job store "default"
2018-01-16 09:07 - INFO - apscheduler.executors.default - Job "DuelLinkRunTime.main.<locals>.in_main (trigger: date[2018-01-16 09:05:51 PST], next run at: 2018-01-16 09:05:51 PST)" executed successfully
2018-01-16 09:07 - INFO - apscheduler.executors.default - Running job "DuelLinkRunTime.dump (trigger: date[2018-01-16 09:07:23 PST], next run at: 2018-01-16 09:07:23 PST)" (scheduled at 2018-01-16 09:07:23.561138-08:00)
2018-01-16 09:07 - INFO - apscheduler.scheduler - Removed job 6d5161e8766543bfb849ba0f661192bd
2018-01-16 09:07 - DEBUG - bot - Dump Getting Called {'battle_calls': {'beforeStart': [], 'afterStart': [], 'beforeEnd': [], 'afterEnd': []}, 'last_run_at': datetime.datetime(2018, 1, 16, 9, 5, 51, 424088), 'next_run_at': datetime.datetime(2018, 1, 16, 13, 7, 18, 560115), 'playmode': 'autoplay', 'run_now': False, 'stop': False}
2018-01-16 09:07 - INFO - apscheduler.executors.default - Job "DuelLinkRunTime.dump (trigger: date[2018-01-16 09:07:23 PST], next run at: 2018-01-16 09:07:23 PST)" executed successfully
2018-01-16 09:09 - DEBUG - bot - Value stop modified

-----------------------------------------------------------------------------------------------

Thanks,
Alex

**Comment by curtiola** [comment]
In "....\Yugioh-bot" create a new folder and name it "tmp".
It's weird that it hasn't been created already, the installation process should have done this.

**Comment by alexandre0119** [comment]
@curtiola , the \tmp\directly is there already, but the ocr.txt file is not there which is the bot is looking for. Thanks~

**Comment by curtiola** [comment]
Oh, guess I was wrong to assume this would be solved the same way as the missing tmp\\ocr.png lol..
For now, here's mine:
[ocr.txt](https://github.com/will7200/Yugioh-bot/files/1636600/ocr.txt)

**Comment by will7200** [comment]
It appears the ocr is failing since the file is not there. Can you display the contents of your bin folder? Also take a look that at #21.

**Comment by will7200** [comment]
Closing for no response. Assuming it is resolved. Open again if it has not been resolved.

**Comment by alexandre0119** [comment]
Please close, thanks
