### ISSUE TITLE
Error when trying to use Bot on steam 

### ISSUE THREAD

**Issue by koreplay** [will7200/Yugioh-bot#34]
This my log 

User@DESKTOP-FRHCE10 MINGW64 ~/Desktop/steam yogo/Yugioh-bot (master)
$ python main.py bot -s
2018-01-16 19:54 - DEBUG - bot - Value last_run_at modified to 2018-01-16 19:51:                                                                                                                01.144326
2018-01-16 19:54 - INFO - apscheduler.scheduler - Adding job tentatively -- it w                                                                                                                ill be properly scheduled when the scheduler starts
2018-01-16 19:54 - DEBUG - bot - Timeout dump Scheduled
2018-01-16 19:54 - DEBUG - bot - Value next_run_at modified to 2018-01-16 23:51:                                                                                                                02.531605
2018-01-16 19:54 - INFO - apscheduler.scheduler - Removed job 3646395c13bc43aab0                                                                                                                bf5a6c82dcac2d
2018-01-16 19:54 - INFO - apscheduler.scheduler - Adding job tentatively -- it w                                                                                                                ill be properly scheduled when the scheduler starts
2018-01-16 19:54 - DEBUG - bot - Timeout dump Scheduled
2018-01-16 19:54 - DEBUG - bot - Watching C:\Users\User\Desktop\steam yogo\Yugio                                                                                                                h-bot\runTimeOptions.json for runTime Options
2018-01-16 19:54 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dum                                                                                                                p" to job store "default"
2018-01-16 19:54 - INFO - apscheduler.scheduler - Scheduler started
2018-01-16 19:54 - DEBUG - bot - Value next_run_at modified to 2018-01-16 19:54:                                                                                                                55.202134
2018-01-16 19:54 - INFO - apscheduler.scheduler - Removed job 27a2f6dcb76d40ce86                                                                                                                4f8762754e2b9e
2018-01-16 19:54 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dum                                                                                                                p" to job store "default"
2018-01-16 19:54 - DEBUG - bot - Timeout dump Scheduled
2018-01-16 19:54 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.mai                                                                                                                n.<locals>.in_main" to job store "default"
2018-01-16 19:54 - INFO - bot - Tracking C:\Users\User\Desktop\steam yogo\Yugioh                                                                                                                -bot\runTimeOptions.json
2018-01-16 19:54 - INFO - bot - Next run at 2018-01-16T19:54:55.202134
2018-01-16 19:54 - INFO - apscheduler.executors.default - Running job "DuelLinkR                                                                                                                unTime.main.<locals>.in_main (trigger: date[2018-01-16 19:54:55 PST], next run a                                                                                                                t: 2018-01-16 19:54:55 PST)" (scheduled at 2018-01-16 19:54:55.202134-08:00)
2018-01-16 19:54 - INFO - apscheduler.scheduler - Removed job cron_main_at_2018-                                                                                                                01-16T19:54:55.202134
2018-01-16 19:54 - DEBUG - bot - Value last_run_at modified to 2018-01-16 19:54:                                                                                                                55.203409
2018-01-16 19:54 - INFO - apscheduler.scheduler - Removed job 5e18b435724a4067b1                                                                                                                51068eb8ebe0e6
2018-01-16 19:54 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dum                                                                                                                p" to job store "default"
2018-01-16 19:54 - DEBUG - bot - Timeout dump Scheduled
2018-01-16 19:54 - INFO - bot.provider.Steam - Passing Through Start Screen
2018-01-16 19:54 - DEBUG - bot - <class 'ValueError'> duel_links_runtime.py 365
2018-01-16 19:54 - DEBUG - bot - Traceback (most recent call last):
  File "C:\Users\User\Desktop\steam yogo\Yugioh-bot\bot\duel_links_runtime.py",                                                                                                                 line 365, in in_main
    provider.pass_through_initial_screen(True)
  File "C:\Users\User\Desktop\steam yogo\Yugioh-bot\bot\providers\steam\steam.py                                                                                                                ", line 155, in pass_through_initial_screen
    if not self.__is_initial_screen__():
  File "C:\Users\User\Desktop\steam yogo\Yugioh-bot\bot\providers\steam\steam.py                                                                                                                ", line 46, in __is_initial_screen__
    (score, diff) = compare_ssim(original, against, full=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\s                                                                                                                kimage\measure\_structural_similarity.py", line 89, in compare_ssim
    raise ValueError('Input images must have the same dimensions.')
ValueError: Input images must have the same dimensions.

2018-01-16 19:54 - DEBUG - bot - Value next_run_at modified to 2018-01-16 23:54:                                                                                                                55.665714
2018-01-16 19:54 - INFO - apscheduler.scheduler - Removed job 4936f242cd704a5da4                                                                                                                82a833618c98b0
2018-01-16 19:54 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.dum                                                                                                                p" to job store "default"
2018-01-16 19:54 - DEBUG - bot - Timeout dump Scheduled
2018-01-16 19:54 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.mai                                                                                                                n.<locals>.in_main" to job store "default"
2018-01-16 19:54 - INFO - apscheduler.executors.default - Job "DuelLinkRunTime.m                                                                                                                ain.<locals>.in_main (trigger: date[2018-01-16 19:54:55 PST], next run at: 2018-                                                                                                                01-16 19:54:55 PST)" executed successfully
2018-01-16 19:55 - INFO - apscheduler.executors.default - Running job "DuelLinkR                                                                                                                unTime.dump (trigger: date[2018-01-16 19:55:00 PST], next run at: 2018-01-16 19:                                                                                                                55:00 PST)" (scheduled at 2018-01-16 19:55:00.666716-08:00)
2018-01-16 19:55 - INFO - apscheduler.scheduler - Removed job a8a08582df4e46dab0                                                                                                                356075c7e62b8a
2018-01-16 19:55 - DEBUG - bot - Dump Getting Called {'battle_calls': {'afterEnd                                                                                                                ': [], 'afterStart': [], 'beforeStart': [], 'beforeEnd': []}, 'last_run_at': dat                                                                                                                etime.datetime(2018, 1, 16, 19, 54, 55, 203409), 'next_run_at': datetime.datetim                                                                                                                e(2018, 1, 16, 23, 54, 55, 665714), 'run_now': False, 'stop': False, 'playmode':                                                                                                                 'autoplay'}
2018-01-16 19:55 - INFO - apscheduler.executors.default - Job "DuelLinkRunTime.d                                                                                                                ump (trigger: date[2018-01-16 19:55:00 PST], next run at: 2018-01-16 19:55:00 PS                                                                                                                T)" executed successfully

**Comment by koreplay** [comment]
Just to give you insight on how I changed resolution on steam since my monitor is a  bit smaller. Duel link has an .exe that allows you to change the resolution it is in C:\Program Files (x86)\Steam\steamapps\common\Yu-Gi-Oh! Duel Links\DuelLinksConfiguration.exe.

**Comment by will7200** [comment]
I will implement steam resolutions screen expectations for the bot.

**Comment by will7200** [comment]
Added expected resolution in 77a3b7343334ef962b2f557f8db9a14c33a701cc
