### ISSUE TITLE
Error on `python install.py`

### ISSUE THREAD

**Issue by trwnh** [will7200/Yugioh-bot#47]
> Traceback (most recent call last):
>   File "install.py", line 4, in <module>
>     import pip
>   File "C:\Users\trwnh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\__init__.py", line 45, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "C:\Users\trwnh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "C:\Users\trwnh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\download.py", line 40, in <module>
>     from pip._vendor import requests, six
>   File "C:\Users\trwnh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_vendor\requests\__init__.py", line 98, in <module>
>     from . import packages
>   File "C:\Users\trwnh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_vendor\requests\packages.py", line 12, in <module>
>     sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
> KeyError: 'pip._vendor.urllib3.contrib'

**Comment by trwnh** [comment]
Solved -- somehow updated back to pip 9.0.2, reran install_requirements.txt and pip 9.0.1 worked. Perhaps a good idea to explicitly state this in the documentation.
