### ISSUE TITLE
main.py tries to import Nox despite config.ini defining Steam as the provider

### ISSUE THREAD

**Issue by trwnh** [will7200/Yugioh-bot#48]
```
$ python main.py bot -s
C:\Users\trwnh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    cli()
  File "...\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "...\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "...\Python\Python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "...\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "...\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 91, in bot
    dlRuntime = setup_runtime(uconfig)
  File "main.py", line 38, in setup_runtime
    from bot.providers import get_provider
  File "D:\Programs\Yugioh-bot\bot\providers\__init__.py", line 15, in <module>
    from bot.providers.nox import Nox
  File "D:\Programs\Yugioh-bot\bot\providers\nox\__init__.py", line 1, in <module>
    from .nox import Nox
  File "D:\Programs\Yugioh-bot\bot\providers\nox\nox.py", line 6, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'
```

**Comment by will7200** [comment]
This boils down to two things, either tesseract is not properly installed in specified location or tesseract is not installed. The install script points to the directory it should have been installed into. Reference #21 and #41 as they are similar issues.

**Comment by will7200** [comment]
I made the import structure to import all bot providers, it just happened that the Nox provider was the first one on the list to give an error, so that is not an issue.

**Comment by will7200** [comment]
Added pywin32 reference in 42e1273f528f64db7eda904f8984575b769e21ed

**Comment by will7200** [comment]
Closing due to no response. Open again if is needed.
