### ISSUE TITLE
Steam Unmatched resolution of 1600-908 expected 1600-900

### ISSUE THREAD

**Issue by ICEET** [will7200/Yugioh-bot#60]
C:\Users\X>cd /d F:\Temp\test\Yugioh-bot-0.6.0

F:\Temp\test\Yugioh-bot-0.6.0>python main.py gui -s
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-04-29 00:04:47 - INFO - bot - APScheduler failed to schedule run, forcing run now
2018-04-29 00:04:47 - DEBUG - bot - Value run_now modified
2018-04-29 00:04:47 - DEBUG - bot - Value stop modified
2018-04-29 00:04:47 - INFO - apscheduler.scheduler - Scheduler started
2018-04-29 00:04:47 - INFO - bot.provider.Steam - Starting Steam...
2018-04-29 00:04:51 - CRITICAL - bot - Could not get a provider, take a look at your config file
2018-04-29 00:04:51 - CRITICAL - bot - Unmatched resolution of 1600-908 expected 1600-900
2018-04-29 00:04:51 - DEBUG - bot - Traceback (most recent call last):
  File "main.py", line 47, in setup_runtime
    dlRuntime.set_provider(get_provider(uconfig.get('bot', 'provider'))(scheduler, uconfig, dlRuntime))
  File "F:\Temp\test\Yugioh-bot-0.6.0\bot\providers\steam\steam.py", line 47, in __init__
    self.ensure_resolutions_matches()
  File "F:\Temp\test\Yugioh-bot-0.6.0\bot\providers\steam\steam.py", line 142, in ensure_resolutions_matches
    "Unmatched resolution of {}-{} expected {}-{}".format(width, height, pre_width, pre_height))
  File "F:\Temp\test\Yugioh-bot-0.6.0\bot\common.py", line 65, in bot_assertion
    raise error_type(message)
bot.providers.BotSetupError: Unmatched resolution of 1600-908 expected 1600-900

2018-04-29 00:05:47 - INFO - bot - APScheduler failed to schedule run, forcing run now
2018-04-29 00:06:47 - INFO - bot - APScheduler failed to schedule run, forcing run now

**Comment by joe159119** [comment]
Start your game before run the bot.
Change your resolution to another one and then change to 1600-900.
Click Enter.
For me is worked.

**Comment by will7200** [comment]
Yeah right now it only supports the ones that I manually have put it. It takes time to do those. I will probably add documentation on how to contribute to adding other screens.

**Comment by BullyWiiPlaza** [comment]
My `Duel Links`' (`Steam` version) screen resolution is set to `1600x900` but I still get this error:
`bot.providers.BotSetupError: Unmatched resolution of 1600-877 expected 1600-900`
@joe159119 's suggestion worked though.
