### ISSUE TITLE
Help , bot error " clean version is wrong "

### ISSUE THREAD

**Issue by salvatore1994** [will7200/Yugioh-bot#66]
Hi , im hving problem , this is what huppens when i try to execute the bot
`MINGW64 ~/Downloads/dlbot/dlbot
$ ./dlbot.exe gui -s
2018-05-23 10:22:58,681 - bot - CRITICAL - Clean version is wrong (0) cannot be zero something happened
2018-05-23 10:22:58,682 - bot - CRITICAL - Try running git reset --hard origin/master
Traceback (most recent call last):
  File "main.py", line 162, in <module>
  File "site-packages\click\core.py", line 722, in __call__
  File "site-packages\click\core.py", line 697, in main
  File "site-packages\click\core.py", line 1066, in invoke
  File "site-packages\click\core.py", line 895, in invoke
  File "site-packages\click\core.py", line 535, in invoke
  File "main.py", line 129, in gui
  File "main.py", line 39, in setup_runtime
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\Users\wf08\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bot\providers\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\Users\wf08\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bot\providers\nox\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\Users\wf08\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bot\providers\nox\nox.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "C:\Users\wf08\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "bot\providers\nox\predefined.py", line 24, in <module>
  File "bot\providers\nox\predefined.py", line 53, in NoxPredefined
  File "site-packages\deprecation.py", line 131, in deprecated
  File "distutils\version.py", line 40, in __init__
  File "distutils\version.py", line 137, in parse
ValueError: invalid version number '0'
[8312] Failed to execute script main
`
can anyone help me ?

**Comment by will7200** [comment]
Hi @salvatore1994 ,
I fixed this in d617e7af89d89b1637c78cd41dcd8f116990970f. It back falls to a file.
I tried updating the executable to reflect this change but now it is getting a codec error.
Need to spend some more time on this. I would use git method for now.
