### ISSUE TITLE
help this error please

### ISSUE THREAD

**Issue by mranugool** [will7200/Yugioh-bot#68]
my log

PS D:\Yugioh-bot> python main.py bot -s
C:\Program Files (x86)\Python36-32\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-07 09:27:06 - INFO - bot - APScheduler failed to schedule run, forcing run now
2018-06-07 09:27:06 - DEBUG - bot - Value stop modified
2018-06-07 09:27:06 - DEBUG - bot - Value run_now modified
2018-06-07 09:27:06 - INFO - apscheduler.scheduler - Scheduler started
2018-06-07 09:27:06 - DEBUG - bot - Value next_run_at modified to 2018-06-07 09:27:07.758838
2018-06-07 09:27:06 - INFO - apscheduler.scheduler - Added job "DuelLinkRunTime.in_main" to job store "default"
2018-06-07 09:27:06 - INFO - bot - Next run at 2018-06-07T09:27:07.758838
2018-06-07 09:27:07 - INFO - apscheduler.executors.default - Running job "DuelLinkRunTime.in_main (trigger: date[2018-06-07 09:27:07 +07], next run at: 2018-06-07 09:27:07 +07)" (scheduled at 2018-06-07 09:27:07.758838+07:00)
2018-06-07 09:27:07 - INFO - apscheduler.scheduler - Removed job cron_main_at_2018-06-07T09:27:07.758838
2018-06-07 09:27:07 - DEBUG - bot - Value last_run_at modified to 2018-06-07 09:27:07.760828
2018-06-07 09:27:07 - INFO - bot.provider.Nox - Starting Nox...
2018-06-07 09:27:39 - INFO - bot.provider.Nox - Passing Through Start Screen
2018-06-07 09:27:39 - INFO - bot.provider.Nox - Waiting for DuelLinks Landing Page
2018-06-07 09:27:59 - DEBUG - bot - <class 'concurrent.futures._base.TimeoutError'> duel_links_runtime.py 434
2018-06-07 09:27:59 - DEBUG - bot - Traceback (most recent call last):
  File "D:\Yugioh-bot\bot\duel_links_runtime.py", line 434, in in_main
    provider.pass_through_initial_screen(False)
  File "D:\Yugioh-bot\bot\providers\nox\nox.py", line 125, in pass_through_initial_screen
    self.__is_initial_screen__, timeout=20)
  File "D:\Yugioh-bot\bot\providers\provider.py", line 280, in __generic_wait_for__
    return future.result(timeout)
  File "C:\Program Files (x86)\Python36-32\lib\concurrent\futures\_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

2018-06-07 09:27:59 - INFO - apscheduler.executors.default - Job "DuelLinkRunTime.in_main (trigger: date[2018-06-07 09:27:07 +07], next run at: 2018-06-07 09:27:07 +07)" executed successfully
2018-06-07 09:29:06 - DEBUG - bot - Value stop modified
2018-06-07 09:29:06 - INFO - bot - Shutdown started
2018-06-07 09:29:06 - INFO - apscheduler.scheduler - Scheduler has been shut down
2018-06-07 09:29:06 - INFO - bot - Shutdown complete
2018-06-07 09:29:06 - INFO - bot - Exiting Yugioh-DuelLinks Bots

Why it does not work What do I have to do?

**Comment by will7200** [comment]
This appears to be a timeout, was Yugioh already running at this point? If not trying have the app open already to where the NPCs appear.

**Comment by mranugool** [comment]
I will try as you suggest.
