### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AIRuni** [will7200/Yugioh-bot#7]
C:\Windows\System32\Yugioh-bot>python main.py bot -s
2017-11-28 04:12:32,754 - bot.debug_helpers - DEBUG - Setup Complete
2017-11-28 04:12:32,754 - bot - DEBUG - Setup Complete
2017-11-28 04:12 - DEBUG - bot - Watching C:\Windows\System32\Yugioh-bot\runTimeOptions.json for runTime Options
2017-11-28 04:12 - INFO - apscheduler.scheduler - Scheduler started
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    cli()
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 76, in bot
    dlRuntime.set_provider(get_provider(uconfig.get('bot', 'provider'))(scheduler, uconfig, dlRuntime))
  File "C:\Windows\System32\Yugioh-bot\bot\providers\provider.py", line 37, in __init__
    self.setUp()
  File "C:\Windows\System32\Yugioh-bot\bot\providers\nox\nox.py", line 22, in setUp
    self.predefined = NoxPredefined(self._config, nox_current_version)
  File "C:\Windows\System32\Yugioh-bot\bot\providers\duellinks.py", line 108, in __init__
    self.get_cache()
  File "C:\Windows\System32\Yugioh-bot\bot\providers\duellinks.py", line 128, in get_cache
    self.generate()
  File "C:\Windows\System32\Yugioh-bot\bot\providers\nox\predefined.py", line 25, in generate
    temp_dict = self.generate_autoduel_stats()
  File "C:\Windows\System32\Yugioh-bot\bot\providers\nox\predefined.py", line 54, in generate_autoduel_stats
    a = self.get_image_stats(cv2.imread(autodueloff), **self.autoduel)
  File "C:\Windows\System32\Yugioh-bot\bot\providers\duellinks.py", line 179, in get_image_stats
    crop_img = img[top:(top + height), left:(left + width)]
TypeError: 'NoneType' object is not subscriptable
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 92, in __del__
    self._loop.call_exception_handler(context)
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1283, in call_exception_handler
    self.default_exception_handler(context)
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1258, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: 'Task was destroyed but it is pending!\ntask: <Task pending coro=<DuelLinkRunTime.periodic() running at C:\\Windows\\System32\\Yugioh-bot\\bot\\duel_links_runtime.py:362>>'
Arguments: ()
Exception ignored in: <bound method DuelLinkRunTime.__del__ of <bot.duel_links_runtime.DuelLinkRunTime object at 0x000002ECC3686AC8>>
Traceback (most recent call last):
  File "C:\Windows\System32\Yugioh-bot\bot\duel_links_runtime.py", line 374, in __del__
  File "C:\Windows\System32\Yugioh-bot\bot\debug_helpers\helpers_decorators.py", line 28, in wrapper
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 1442, in getouterframes
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 1415, in getframeinfo
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 755, in findsource
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 721, in getmodule
KeyError: '__main__'

**Comment by will7200** [comment]
This is most likely an issue with reading the image from the assets directory, if you are using the config file from the master branch you need to change the home directory to where you cloned this repo on your computer.

**Comment by AIRuni** [comment]
I changed config.ini,but errored. Maybe the cause of the error is opencv+contrib version. (http://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv)←There is already not [cv2+contrib 3.2.0]version, so I am using "pip install opencv-contrib-python".
[locations]
assets = C:\Users\ooog\DuelLinksBot\assets
cache_file = C:\Users\ooog\DuelLinksBot\assets\predefined.h5
home = C:\Users\ooog\DuelLinksBot
bin = C:\Users\ooog\DuelLinksBot\bin
log = C:\Users\ooog\DuelLinksBot\log

[bot]
killnoxondone = True
runtimepersistence = runTimeOptions.json
provider = Choose
startbotonstartup = False
noxlocation = C:\Program Files (x86)\Nox\bin

C:\Windows\System32\Yugioh-bot>python main.py bot -s
2017-11-28 11:51:11,178 - bot.debug_helpers - DEBUG - Setup Complete
2017-11-28 11:51:11,179 - bot - DEBUG - Setup Complete
2017-11-28 11:51 - DEBUG - bot - Watching C:\Windows\System32\Yugioh-bot\runTimeOptions.json for runTime Options
2017-11-28 11:51 - INFO - apscheduler.scheduler - Scheduler started
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    cli()
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 76, in bot
    dlRuntime.set_provider(get_provider(uconfig.get('bot', 'provider'))(scheduler, uconfig, dlRuntime))
  File "C:\Windows\System32\Yugioh-bot\bot\providers\__init__.py", line 16, in get_provider
    [x.__str__() for x in available_providers])))
Exception: Provider Choose does not exist, choose from [Nox,Steam]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 92, in __del__
    self._loop.call_exception_handler(context)
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1283, in call_exception_handler
    self.default_exception_handler(context)
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1258, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: 'Task was destroyed but it is pending!\ntask: <Task pending coro=<DuelLinkRunTime.periodic() running at C:\\Windows\\System32\\Yugioh-bot\\bot\\duel_links_runtime.py:362>>'
Arguments: ()
Exception ignored in: <bound method DuelLinkRunTime.__del__ of <bot.duel_links_runtime.DuelLinkRunTime object at 0x0000023B53CA6A20>>
Traceback (most recent call last):
  File "C:\Windows\System32\Yugioh-bot\bot\duel_links_runtime.py", line 374, in __del__
  File "C:\Windows\System32\Yugioh-bot\bot\debug_helpers\helpers_decorators.py", line 28, in wrapper
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 1442, in getouterframes
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 1415, in getframeinfo
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 755, in findsource
  File "C:\Users\時崎 狂三\AppData\Local\Programs\Python\Python35\lib\inspect.py", line 721, in getmodule
KeyError: '__main__'

**Comment by will7200** [comment]
So go ahead and re-clone master, I updated the config file so the home directory is relative path of a clone repository instead of my full path.

https://github.com/will7200/Yugioh-bot/commit/61246766a47794f151087e995d231fac2ed00026
https://github.com/will7200/Yugioh-bot/commit/70a40b43a55c1b68975cd849d2ad957a2ae25559
https://github.com/will7200/Yugioh-bot/commit/793d6d6b0e67f2d0be49c1ace2c25a243a8da936

**Comment by AIRuni** [comment]
* daemon not running. starting it now on port 5037 *
Cannot create process: cannot find the path specified (3)
* failed to start daemon *
error: cannot connect to daemon
2017-11-28 20:03 - DEBUG - bot.provider.Nox - Tapping at location (240,540)
error: no devices/emulators found

**Comment by will7200** [comment]
This is an issue with adb debug tool not the program. In a command  prompt, after you opened nox, list the devices using adb and make sure the device is registered.
What exactly do you mean that the Nox player stops at 99%? Do nox fail to start entirely?

**Comment by AIRuni** [comment]
adb device list→https://imgur.com/a/SfAMo
Nox App Player stuck at 99% →https://imgur.com/aW6TYYh

**Comment by will7200** [comment]
Ok this is a nox issue then. I did some googling and found some potential fixes. I would first try uinstalling and installing again if that not an issue, otherwise here are some links.
http://noxappplayerdownload.com/fix-nox-app-player-stuck-99-virtual-machine-error-system-fail-start-please-contact-customer-service/
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjHtrCM9-bXAhWD2YMKHQPXA48QtwIIOjAD&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DllmeIzm5XGQ&usg=AOvVaw0iugYEbrFimiAZ6g_4kRsc

**Comment by AIRuni** [comment]
2017-11-30 04:35 - INFO - bot.provider.Nox - Starting Nox...
2017-11-30 04:35 - DEBUG - bot.debug_helpers - Called by: []
2017-11-30 04:35 - DEBUG - bot - Dump Getting Called {'run_now': False, 'last_run_at': datetime.datetime(2017, 11, 30, 4, 35, 17, 401631), 'next_run_at': datetime.datetime(2017, 11, 30, 4, 35, 17, 398582), 'stop': False, 'battle_calls': {'beforeStart': [], 'afterEnd': [], 'afterStart': [], 'beforeEnd': []}}
2017-11-30 04:35 - ERROR - asyncio - Exception in callback async_calling_function.<locals>.calling_functionn.<locals>.wrapper()
handle: <TimerHandle when=129265.078 async_calling_function.<locals>.calling_functionn.<locals>.wrapper()>
Traceback (most recent call last):
  File "C:\Users\ooog\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 126, in _run
    self._callback(*self._args)
  File "C:\Windows\System32\Yugioh-bot\bot\debug_helpers\helpers_decorators.py", line 34, in wrapper
    return __function(*args, **kwargs)
  File "C:\Windows\System32\Yugioh-bot\bot\duel_links_runtime.py", line 259, in dump
    write_data_file(tmpdict, self._file)
  File "C:\Windows\System32\Yugioh-bot\bot\utils\data.py", line 69, in write_data_file
    with open(file, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\System32\\Yugioh-bot\\runTimeOptions.json'
2017-11-30 04:35 - INFO - bot.provider.Nox - Passing Through Start Screen

**Comment by will7200** [comment]
I believe you are running this in a folder directory that requires admin rights, so either change the directory to something that you own or start the command prompt as admin
